language: python
matrix:
    allow_failures:
        - os: osx
    include:
        - os: osx
          language: generic
        - os: linux
          sudo: required
          python: 3.4
        - os: linux
          sudo: required
          python: 2.7
before_install:
  - ./.travis/before_install.sh
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: python test/test_load_module.py -v
