language: python
python:

  - "2.7"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  # - "pypy"
before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: pytest -t test
