name: Tests CUDA

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'    
  push:
    branches:
      - 'master'  
  create:
    branches:
      - 'master'
    tags:
      - '**'

jobs:
  linux-cuda:

    runs-on: pc-cuda
    if: "!contains(github.event.head_commit.message, 'no ci')"

    steps:
    - uses: actions/checkout@v1
    - name: Install POT
      run: |
        python3.10 -m pip install  --ignore-installed -e .
    - name: Run tests
      run: |
        python3.10 -m pytest --durations=20 -v test/ ot/ --doctest-modules --color=yes 

