name: Tests CUDA

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'    
  push:
    branches:
      - 'master'  
  create:
    branches:
      - 'master'
    tags:
      - '**'

jobs:
  linux-cuda:

    runs-on: pc-cuda
    if: "!contains(github.event.head_commit.message, 'no ci')"

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install POT
      run: |
        pip install -e .
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/requirements_cuda.txt
        pip install pytest pytest-cov
    - name: Run tests
      run: |
        python -m pytest --durations=20 -v test/ ot/ --doctest-modules --color=yes --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
